### ISSUE TITLE
add protocol config option to the env variables

### ISSUE THREAD

**Issue by chaos-adept** [spaceshipyard/mars-rover-node-bridge#18]

**Comment by chaos-adept** [comment]
@vicnbt 
it is important to update script on your raspberry device to the full path url, and the https protocol.
Example:
```
#!/bin/bash

export dispatcherUrl=https://mars-rover.org:8080
#
#export host=192.168.1.46

export room=lobby123
export export statusHandlers=led/led-status-handlers

npm run start:watch

```

**Comment by vicnbt** [comment]
https://github.com/spaceshipyard/mars-rover-dispatcher/blob/master/runall.default.sh could be updated

**Comment by chaos-adept** [comment]
@vicnbt  it will be fixed in the https://github.com/spaceshipyard/mars-rover-dispatcher/issues/8
