### ISSUE TITLE
Implement arduino module for motor encoder sensors

### ISSUE THREAD

**Issue by chaos-adept** [spaceshipyard/mars-rover-node-bridge#24]
It is required to implement support of reading from pins by using:
Sensor API - http://johnny-five.io/api/sensor/

Input:
two analog pins with value: 0-1023, which is means wheel rotation per minute.

Output:
sensor data message by analogy with proximity
`eventBus.emit(EVENT_SENSOR_DATA, {type: SENSOR_DATA_MOTORENCODERS, data})`
where `data`:
`{ left: <rotation_per_minute>, right: <rotation_per_minute> }`

exact pins will be provided later by @vnabatov so far any two free analog pins might be selected for development.

**Comment by vnabatov** [comment]
added standardjs auto fix, having problems with passing the signal from uno2-pin3 to uno1-pin-A2 (no reaction) investigating
