### ISSUE TITLE
Migrate node bridge to standartjs

### ISSUE THREAD

**Issue by chaos-adept** [spaceshipyard/mars-rover-node-bridge#8]
for reference - https://standardjs.com/

**Comment by vicnbt** [comment]
code looks much nicer
all done, need to test (have no device left it at work)

**Comment by chaos-adept** [comment]
@vicnbt  Could you push your changes in the "feature" branch?

**Comment by chaos-adept** [comment]
it makes sense to add standartjs badge to the readme file https://standardjs.com/#is-there-a-readme-badge. 
changes in general are fine, the pull requiest could be created.
